### ISSUE TITLE
remove localStorage

### ISSUE THREAD

**Issue by luisrudge** [luisrudge/next.js-auth0#10]

**Comment by balupton** [comment]
great work with the project - stumbled across this too - why was local storage added as well as cookies? what was the rationale for both?

**Comment by luisrudge** [comment]
I started with only localStorage, then quickly figured it out that I'd need cookies to send the token to the server as well.. I ended up leaving both 😭

**Comment by luisrudge** [comment]
Because I need to render authenticated views in the server as well and the server can't read the local storage

**Comment by luisrudge** [comment]
fixed in https://github.com/luisrudge/next.js-auth0/pull/21
