### ISSUE TITLE
Error when using next.js-auth0 with LinkedIn: "The generated token is too large. Try with more specific scopes."

### ISSUE THREAD

**Issue by jimthedev** [luisrudge/next.js-auth0#14]
I'm using the current master version of this project. The only difference is that I have LinkedIn enabled as a provider. The same form works when using Facebook or the default Auth0 login provider. After clicking LinkedIn I get the following error.

"The generated token is too large. Try with more specific scopes."

**Comment by luisrudge** [comment]
Maybe linkedin has too many info in their default user. Try adding specific scopes like `scope: 'openid email about birthday location work education about'`.

**Comment by AriLFrankel** [comment]
I just experienced this myself. I wonder if you disabled the feature on your Auth0 client of being OIDC compliant. This would lead to the same issue if no other changes were made.
