### ISSUE TITLE
Logout not working

### ISSUE THREAD

**Issue by james-ff** [luisrudge/next.js-auth0#24]
In a cloned copy of this project set up according to the ReadMe:
- when I sign in with a database account I get the following error: "access_denied: Password login is disabled for clients using externally hosted login pages with oidc_conformant flag set.".
- when I sign in with a social account, both sign in and off work fine.

In my own project set up based on this project:
- I can sign in with all account types ok, but on every sign off I get the following error:

![screen shot 2018-01-16 at 15 50 34](https://user-images.githubusercontent.com/1874352/34998901-30d54610-fad8-11e7-8800-f23a9ac7f411.png)

![screen shot 2018-01-16 at 15 50 53](https://user-images.githubusercontent.com/1874352/34998911-36de9bf6-fad8-11e7-9994-68c36b08f34d.png)

Any Ideas concerning any of these issues would be massively appreciated!

Many Thanks!

**Comment by james-ff** [comment]
Update: In my own project I changed the version of auth0-lock to v10.18 and I now get the same error as in this project

**Comment by luisrudge** [comment]
Can you send a PR upgrading this to the latest version (v11.x)? That would help a lot!

**Comment by luisrudge** [comment]
Actually, it'd be great to have this updated to the latest versions of all the packages, including react and nextjs as well

**Comment by luisrudge** [comment]
As for the logout thing, I have absolutely no idea what's going on 😝

**Comment by james-ff** [comment]
Have updated this library for React 16, Next 4, and other libs, according to my testing the functionality is the same, no bugs as far as I can see and is visually identical. Will now look into updating auth0-lock (have left that one out to ensure that updating the other libraries went smoothly first)

**Comment by james-ff** [comment]
Everything seems ok now apart from the token issue, do you know where / who I can go to for this? @luisrudge

**Comment by luisrudge** [comment]
You forgot to update auth0-lock though. maybe that's the issue?

**Comment by luisrudge** [comment]
oh, sorry. I just saw your latest PR 😝  does it work with the latest lock?

**Comment by james-ff** [comment]
In a clone of this project everything works. In my own project I have the token issue on sign off.

**Comment by luisrudge** [comment]
That's very weird indeed.  Can you put your project on github so I can take a look? Or, if you can't, put a repro project on github. I'll close this issue since this repo itself is working, but let's try to find your issue

**Comment by james-ff** [comment]
@luisrudge I feel silly, I had copied the code for the signed-in.js file into the sign-off.js file by mistake (I needed a night of sleep to come back and see it). It all now works! Thanks for this project and the swift responses! I'm glad to be able to contribute to its development

**Comment by luisrudge** [comment]
I'm glad you found the issue! 🎉
