### ISSUE TITLE
Warning: getDefaultProps is only used on classic React.createClass definitions

### ISSUE THREAD

**Issue by sedubois** [luisrudge/next.js-auth0#3]
This is produced multiple times in the console when loading the lock:

`Warning: getDefaultProps is only used on classic React.createClass definitions. Use a static property named `defaultProps` instead.`

**Comment by luisrudge** [comment]
Yeah, this is probably something with the Lock component itself.. Not much I can do about that.

**Comment by sedubois** [comment]
I didn't see this beahviour when using auth0-lock on top of react-boilerplate. So there seems to be something specific to Next. We should maybe ask Auth0.

**Comment by luisrudge** [comment]
are you using the latest react version?

**Comment by luisrudge** [comment]
probably related to this: https://github.com/christianalfoni/formsy-react/issues/168#issuecomment-149321936

**Comment by sedubois** [comment]
The example uses React 15.3.2, so yes the latest: https://github.com/sedubois/belong/blob/master/package.json#L228

**Comment by sedubois** [comment]
Oh interesting, yes I read in some other Next issue that React is included twice. Where was that?

**Comment by sedubois** [comment]
OK here: https://github.com/zeit/next.js/issues/204

**Comment by luisrudge** [comment]
Ahh, thanks for catching that. I'll keep an eye on it!

**Comment by jimthedev** [comment]
@sedubois @luisrudge They seem to have fixed it in Next but I'm still having the issue in next.js-auth0. Are you as well?

**Comment by luisrudge** [comment]
I just upgraded everything to the latest version (and added styled-components since the old `next/css` thing was removed). It's all working right now.

**Comment by jimthedev** [comment]
@luisrudge Nice work! It seems to work great. One error I get in the server side console is: `Client pings, but there's no entry for page: /login` but as soon as I create a login page it stops.  I'm not sure what keeps requesting that page.

**Comment by luisrudge** [comment]
I'm not having this issue with this project :|

**Comment by jimthedev** [comment]
Cool. I'll work on it.
