### ISSUE TITLE
This repo seems very insecure?

### ISSUE THREAD

**Issue by yn5** [luisrudge/next.js-auth0#30]
Not to be an ass or anything. I am in the process of securing a Next.js project myself and I am having the same problem, stumbled upon this repo looking for examples on how to fix this. 

But it seems the same problem lives in this repo:
Set a cookie with the name 'user' with the value test, navigate to about and back to home with the navigation in the page header and you see the super secret div.

So I don't have a solution ready either, hoping this is a good place to discuss the issue.

Indeed, the 'malicious' user would still have to guess what cookie to set if he doesn't have access to the codebase, but to me that does not seem secure to me, or am I maybe wrong here?

Normally I'm not too bothered securing client routes since I have my data secured on a server where accessTokens get validated. But since it is Next.js  which can do SSR it seemed like a good chance to crank up security a bit, but I'm having a hard time securing client side navigation without verifying the accessToken on every page transition (which seems a little too much for me). Maybe I am just wishful thinking here, would love to hear that too.

**Comment by qmeteor** [comment]
I'm curious about this too. But when you do that on the production site it doesn't seem to be an issue. Anyone more knowledgeable care to explain why that is the case?

**Comment by luisrudge** [comment]
You have to validate the JWT/access token when you do your API requests (possibly to another endpoint). In an ideal example, the "super secret div" would actually try to fetch something from an API and fail because whatever you set in the `jwt` cookie isn't valid.
