### ISSUE TITLE
Does not work in iOS Safari with free account

### ISSUE THREAD

**Issue by tim-phillips** [luisrudge/next.js-auth0#32]
Since third-party cookies are disabled in Safari by default, and since `auth0-lock@11` uses cross-origin authentication (requiring cross-domain cookies), the two are incompatible with each other without paying for a pro account and enabling custom domains.

**Comment by luisrudge** [comment]
yes. I still need to upgrade this to use the Universal Login Page. Do you want to send a PR?

**Comment by tim-phillips** [comment]
I'm hacking on this on my own project. Once I get it figured out I'll make an attempt at a PR.

**Comment by tim-phillips** [comment]
Would you like to keep it functional or use the class based approach that auth0 uses at https://auth0.com/docs/quickstart/spa/react ?

**Comment by luisrudge** [comment]
I think there's no need to have that here, considering we just need to redirect to the Universal Login Page and parse the hash callback. What do you think?

**Comment by tim-phillips** [comment]
Yeah that sounds good
