### ISSUE TITLE
_auth0Js2.default is undefined

### ISSUE THREAD

**Issue by BlakeEric** [luisrudge/next.js-auth0#33]
Thanks for creating this example!

I'm getting the following error when attempting to visit the sign-in page. Any help would be appreciated.

`_auth0Js2.default is undefined
Auth0APIClient@http://localhost:3000/_next/1531520081709/page/auth/sign-in.js:38946:7
setupClient@http://localhost:3000/_next/1531520081709/page/auth/sign-in.js:24794:28
setupLock@http://localhost:3000/_next/1531520081709/page/auth/sign-in.js:23363:3
Base@http://localhost:3000/_next/1531520081709/page/auth/sign-in.js:28444:14
Auth0Lock@http://localhost:3000/_next/1531520081709/page/auth/sign-in.js:32607:50
getLock@http://localhost:3000/_next/1531520081709/page/auth/sign-in.js:32381:10
show@http://localhost:3000/_next/1531520081709/page/auth/sign-in.js:32406:10
componentDidMount@http://localhost:3000/_next/1531520081709/page/auth/sign-in.js:32313:8
commitLifeCycles@http://localhost:3000/_next/1531520081709/commons.js:8776:15
commitAllLifeCycles@http://localhost:3000/_next/1531520081709/commons.js:9952:9
callCallback@http://localhost:3000/_next/1531520081709/commons.js:548:9
invokeGuardedCallbackDev@http://localhost:3000/_next/1531520081709/commons.js:587:7
invokeGuardedCallback@http://localhost:3000/_next/1531520081709/commons.js:444:5
commitRoot@http://localhost:3000/_next/1531520081709/commons.js:10056:9
performWorkOnRoot@http://localhost:3000/_next/1531520081709/commons.js:11023:42
performWork@http://localhost:3000/_next/1531520081709/commons.js:10973:7
requestWork@http://localhost:3000/_next/1531520081709/commons.js:10884:7
scheduleWorkImpl@http://localhost:3000/_next/1531520081709/commons.js:10738:11
scheduleWork@http://localhost:3000/_next/1531520081709/commons.js:10695:12
scheduleTopLevelUpdate@http://localhost:3000/_next/1531520081709/commons.js:11199:5
updateContainer@http://localhost:3000/_next/1531520081709/commons.js:11237:7
renderSubtreeIntoContainer@http://localhost:3000/_next/1531520081709/commons.js:15235:5
render@http://localhost:3000/_next/1531520081709/commons.js:15296:12
renderReactElement@http://localhost:3000/_next/1531520081709/main.js:17670:5
_callee4$@http://localhost:3000/_next/1531520081709/main.js:17436:13
tryCatch@http://localhost:3000/_next/1531520081709/main.js:6178:37
invoke@http://localhost:3000/_next/1531520081709/main.js:6412:22
defineIteratorMethods/</prototype[method]@http://localhost:3000/_next/1531520081709/main.js:6230:16
step@http://localhost:3000/_next/1531520081709/main.js:1854:22
module.exports</exports.default/</<@http://localhost:3000/_next/1531520081709/main.js:1872:14
Promise@http://localhost:3000/_next/1531520081709/main.js:7051:7
module.exports</exports.default/<@http://localhost:3000/_next/1531520081709/main.js:1851:12
doRender@http://localhost:3000/_next/1531520081709/main.js:17449:12
_callee2$@http://localhost:3000/_next/1531520081709/main.js:17303:20
tryCatch@http://localhost:3000/_next/1531520081709/main.js:6178:37
invoke@http://localhost:3000/_next/1531520081709/main.js:6412:22
defineIteratorMethods/</prototype[method]@http://localhost:3000/_next/1531520081709/main.js:6230:16
step@http://localhost:3000/_next/1531520081709/main.js:1854:22
module.exports</exports.default/</<@http://localhost:3000/_next/1531520081709/main.js:1872:14
Promise@http://localhost:3000/_next/1531520081709/main.js:7051:7
module.exports</exports.default/<@http://localhost:3000/_next/1531520081709/main.js:1851:12
render@http://localhost:3000/_next/1531520081709/main.js:17333:12
_callee$/<@http://localhost:3000/_next/1531520081709/main.js:17646:13
notify/<@http://localhost:3000/_next/1531520081709/main.js:11269:16
module.exports</module.exports/</<@http://localhost:3000/_next/1531520081709/main.js:5425:22
notify@http://localhost:3000/_next/1531520081709/main.js:11268:7
set@http://localhost:3000/_next/1531520081709/main.js:11010:7
_callee3$@http://localhost:3000/_next/1531520081709/main.js:10860:17
tryCatch@http://localhost:3000/_next/1531520081709/main.js:6178:37
invoke@http://localhost:3000/_next/1531520081709/main.js:6412:22
defineIteratorMethods/</prototype[method]@http://localhost:3000/_next/1531520081709/main.js:6230:16
step@http://localhost:3000/_next/1531520081709/main.js:1854:22
step/<@http://localhost:3000/_next/1531520081709/main.js:1865:13
run@http://localhost:3000/_next/1531520081709/main.js:6947:22
notify/<@http://localhost:3000/_next/1531520081709/main.js:6960:28
flush@http://localhost:3000/_next/1531520081709/main.js:7216:9`

**Comment by luisrudge** [comment]
Hi! This is already being fixed. It's not an issue with this repo, but with auth0-lock

**Comment by BlakeEric** [comment]
Thanks for the reply! Do you have a link to the issue over at the auth0-lock repo?

**Comment by luisrudge** [comment]
Yes: https://github.com/auth0/lock/issues/1433
