### ISSUE TITLE
Warning: getInitialState was defined on ReactTransitionGroup

### ISSUE THREAD

**Issue by sedubois** [luisrudge/next.js-auth0#4]
This is produced twice in the console when loading the lock:

`Warning: getInitialState was defined on ReactTransitionGroup, a plain JavaScript class. This is only supported for classes created using React.createClass. Did you mean to define a state property instead?`

**Comment by luisrudge** [comment]
Yeah, this is probably something with the Lock component itself.. Not much I can do about that.

**Comment by sedubois** [comment]
See https://github.com/luisrudge/next.js-auth0/issues/3#issuecomment-259142477
