### ISSUE TITLE
Question about HOC with getInitialProps

### ISSUE THREAD

**Issue by LeonBlade** [luisrudge/next.js-auth0#8]
I haven't cloned your repo but I have copied the important files to make the project work, namely the HOCs for default and authed pages.

I've tried to use an async getInitialProps and the call goes out as it's called by the parent HOC, but I'm not seeing it transfer through to the child (the page) when I try to fetch the data from the request.

I'm using the `isomorphic-fetch` package.  I'm new to isomorphic design and next.js, I know you are not support for Next.js or any of this.  However, I thought you might have some insight on my problem.

```
class Dashboard extends React.Component {
    static async getInitialProps() {
        const jobs = await fetch('http://localhost:3000/api/jobs');
        const jobs_data = await jobs.json();
        return { _data: jobs_data };
    }

...

export default securePage(Dashboard);
```

Am I supposed to be able to get this data on my component?  I know it works as a normal React component, but when using it with the securePage HOC it fails.

Thank you, and sorry for the trouble.

**Comment by LeonBlade** [comment]
Sorry, I figured out the issue.  I just need to use `async` on each of the `getInitialProps()` methods and use `await` when calling the child `getInitialProps()`.

**Comment by luisrudge** [comment]
I'm glad you figured it out
