### ISSUE TITLE
Csrf? Why localstorage + cookies?

### ISSUE THREAD

**Issue by ndreckshage** [luisrudge/next.js-auth0#9]
Great example! Few questions.

1 - Localstorage + cookies: I get cookies are needed so the server is capable of using `isomorphic-fetch`. Why use both mechanisms, and not just the cookie on the client as well? Localstorage nice for client only apps, but I don't get point for universal?

2 - Csrf: I'm confused how 5693936c29e9654b1e9c5899e610b84eef88538d prevents csrf? The client seems to be generating the uuid, and only prevents `auth/signed-in` auth0 callback? What situation is this preventing?

If the universal app is interacting with a stateless API on different subdomain, passing token via headers, wouldn't csrf be a non-issue? Assuming `getInitialProps` calls safe `GET` requests.

**Comment by luisrudge** [comment]
**1** I started with localStorage only and when I added the cookie, I was running of time and never removed the localStorage strategy 😭 

**2** I had a long discussion on #5, which didn't end with all my questions, but the solution was easy enough and I decided to add. Also, the **XSRF** check follows auth0 guidelines described [here](https://auth0.com/docs/protocols/oauth2/oauth-state)

I'm sorry but I don't fully understand XSRF or CSRF.

**Comment by ndreckshage** [comment]
Thanks for reply! I see you made issue to clean up localstorage. And I'll post a reply on #5
